# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '68624f56-dcd2-420f-a833-253048e417a5'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Web app name
  webAppName: 'tb-housepriceapi'
  # Environment name
  environmentName: 'tb-housepriceapi'

trigger:
- main

pool:
  vmImage: $(vmImageName)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
